version: '2'

services:
  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    networks:
      - my-network
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=study
      - PGDATA=/var/lib/postgresql/data
      # - PGDATA=/var/lib/postgresql/data
    ports: 
      - "5432:5432"

  backend:
    build: ./server
    restart: always
    networks:
      - my-network
    ports: 
      - "5000:5000"
    depends_on:
      - db
    environment:
      - PGDATABASE=study
      - PGUSER=postgres
      - PGPASSWORD=root
      - PGHOST=db
networks:
  my-network:
    name: my-network
volumes:
  db:
    driver: local
  pgdata:
    driver: local

# docker exec db pg_dump -U postgres --column-inserts --data-only  study > inserts.sql
# docker exec db pg_dump -U postgres --column-inserts study > inserts.sql
# docker exec <container-name> pg_dump -U <postgres-user> --column-inserts --data-only <db_name> inserts.sql
