version: '2'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    networks:
      - my-network
    volumes:
      - ./db:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=study
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports: 
      - "5432:5432"

  backend:
    build: ./server
    restart: always
    networks:
      - my-network
    ports: 
      - "5000:5000"
    depends_on:
      - db
    environment:
      - PGDATABASE=study
      - PGUSER=postgres
      - PGPASSWORD=root
      - PGHOST=db
networks:
  my-network:
    name: my-network
volumes:
  db:
    driver: local
  pgdata:
    driver: local
