version: '1.0'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    networks:
      - my-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test1
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports: 
      - "5001:5432"

  backend:
    build: ./server
    restart: always
    networks:
      - my-network
    ports: 
      - "5000:5000"
    links:
      - db
    depends_on:
      - db
    environment:
      - PGDATABASE=test1
      - PGUSER=postgres
      - PGPASSWORD=root
      - PGHOST=db
networks:
  my-network:
    name: my-network
volumes:
  db:
    driver: local
